"""Markdown rendering of an analysis report (used by the export endpoint)."""

from __future__ import annotations

from ..schemas import AnalysisReport

BADGE = {"covered": "✅ covered", "partial": "🟡 partial", "missing": "🔴 missing"}
STATUS = {"pass": "✅", "warn": "🟡", "fail": "🔴"}


def to_markdown(report: AnalysisReport) -> str:
    job = report.job
    s = report.scores
    lines: list[str] = []

    lines.append(f"# FitScope report — {job.role_title or 'Target role'}")
    if job.company:
        lines.append(f"**Company:** {job.company}")
    if report.created_at:
        lines.append(f"**Generated:** {report.created_at}")
    if report.share_url:
        lines.append(f"**Report link:** {report.share_url}")
    lines.append("")

    lines.append("## Scores")
    lines.append("")
    lines.append("| Metric | Score |")
    lines.append("| --- | --- |")
    lines.append(f"| Overall readiness | **{s.overall}/100** |")
    lines.append(f"| Semantic fit | {s.semantic_fit}/100 |")
    lines.append(f"| ATS readiness | {s.ats_readiness}/100 |")
    lines.append(f"| Must-have coverage | {s.must_have_coverage}% |")
    lines.append(f"| Responsibility coverage | {s.responsibility_coverage}% |")
    lines.append(f"| Nice-to-have coverage | {s.nice_to_have_coverage}% |")
    lines.append("")
    lines.append(f"**Verdict: {s.verdict}.** {s.verdict_detail}")
    lines.append("")
    lines.append(
        f"Requirements: {s.covered} covered, {s.partial} partial, {s.missing} missing."
    )
    lines.append("")

    lines.append("## Requirement evidence")
    lines.append("")
    for e in report.evidence:
        lines.append(
            f"### {BADGE[e.coverage]} — {e.requirement.text}"
        )
        lines.append(
            f"*{e.requirement.category.replace('_', ' ')} · relevance {e.score:.2f}*"
        )
        if e.best_bullet_text and e.coverage != "missing":
            lines.append(f"> {e.best_bullet_text}")
        if e.keyword_misses:
            lines.append(f"Missing terms: {', '.join(e.keyword_misses)}")
        lines.append("")

    lines.append("## ATS mechanics")
    lines.append("")
    lines.append("| Check | Result | Points | Detail |")
    lines.append("| --- | --- | --- | --- |")
    for c in report.ats.checks:
        detail = c.detail.replace("|", "/")
        lines.append(
            f"| {c.label} | {STATUS[c.status]} | {c.points}/{c.max_points} | {detail} |"
        )
    lines.append("")
    if report.ats.missing_keywords:
        lines.append("**Keywords absent from the resume:** " + ", ".join(report.ats.missing_keywords))
        lines.append("")

    sug = report.suggestions
    lines.append("## Recommended edits")
    lines.append("")
    if sug.tailored_summary:
        lines.append("**Tailored summary**")
        lines.append("")
        lines.append(f"> {sug.tailored_summary}")
        lines.append("")
    for r in sug.rewrites:
        lines.append(f"- **Before:** {r.original}")
        lines.append(f"  **After:** {r.rewritten}")
        lines.append(f"  *Why:* {r.reason}")
        lines.append("")
    if sug.add_these:
        lines.append("**Add to the resume**")
        lines.append("")
        lines.extend(f"- {item}" for item in sug.add_these)
        lines.append("")
    if sug.quick_wins:
        lines.append("**Quick wins**")
        lines.append("")
        lines.extend(f"- {item}" for item in sug.quick_wins)
        lines.append("")

    pipeline = report.pipeline or {}
    lines.append("---")
    lines.append(
        "Generated by FitScope · retrieval: "
        f"{pipeline.get('retrieval', 'n/a')} · reranker: {pipeline.get('reranker', 'n/a')} · "
        f"JD extraction: {job.extraction_mode} · suggestions: {sug.mode} · "
        f"{report.duration_ms} ms"
    )
    return "\n".join(lines)
